import { Product, ChatSession, UserProfile, Order, AppNotification } from "./types";

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    title: "iPhone 15 Pro (128GB, Space Black) - Unlocked",
    description: "Selling my fully-unlocked space black iPhone 15 Pro. Perfect condition, 100% battery capacity. Protected with glass screen protector since day 1. Includes original box and unused USB-C fast charging braided cable.",
    price: 850,
    originalPrice: 999,
    category: "Electronics",
    condition: "Like New",
    tags: ["iPhone", "Apple", "Smartphones", "Mobile", "Unlocked"],
    image: "https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?auto=format&fit=crop&w=600&q=80",
    sellerId: "sell-99",
    sellerName: "Alice Miller",
    sellerRating: 4.9,
    sellerTrustScore: 97,
    trustRiskRating: "Low",
    status: "active",
    views: 142,
    offersCount: 3,
    likesCount: 18,
    createdAt: "2026-05-18T10:00:00Z",
    trustAnalytics: "Genuine seller with 50+ successful completions. Original receipts scanned. Serial number validated successfully. High Trust ranking.",
  },
  {
    id: "prod-2",
    title: "Sony WH-1000XM4 Noise Canceling Wireless Headphones",
    description: "Selling because I upgraded. Active noise cancellation is completely phenomenal. Battery lasts 30+ hours easily. Comes with carrying case, headphone jack cable, and air travel adapter.",
    price: 180,
    originalPrice: 280,
    category: "Audio & Music",
    condition: "Good",
    tags: ["Headphones", "Sony", "ANC", "Wireless", "Audio"],
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&q=80",
    sellerId: "sell-88",
    sellerName: "Marcus Brody",
    sellerRating: 4.7,
    sellerTrustScore: 91,
    trustRiskRating: "Low",
    status: "active",
    views: 89,
    offersCount: 1,
    likesCount: 12,
    createdAt: "2026-05-15T08:30:00Z",
    trustAnalytics: "Authenticated model. Verified buyer reviews for seller match current coordinates. Account age > 2 years.",
  },
  {
    id: "prod-3",
    title: "Keychron Q1 Mechanical Keyboard (Hot-swappable)",
    description: "Keychron Q1 Pro fully assembled mechanical keyboard. Brown switches, custom tactile feelings. Premium CNC aluminum body with gorgeous sound. Includes coiled cable.",
    price: 130,
    originalPrice: 190,
    category: "Computer Gear",
    condition: "New",
    tags: ["Keyboard", "Mechanical", "Keychron", "Tech", "Custom"],
    image: "https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?auto=format&fit=crop&w=600&q=80",
    sellerId: "sell-55",
    sellerName: "Devin Zhao",
    sellerRating: 4.8,
    sellerTrustScore: 94,
    trustRiskRating: "Low",
    status: "active",
    views: 64,
    offersCount: 0,
    likesCount: 7,
    createdAt: "2026-05-19T14:15:00Z",
    trustAnalytics: "Listing aligns with standard seller inventory. Clear product photoshoot matches standard desk lighting. No generic stock tags found.",
  },
  {
    id: "prod-4",
    title: "Vintage Heavy Suede Leather Jacket - Dark Brown",
    description: "Stunning vintage genuine dark brown suede leather jacket. Warm quilted inner lining. Great streetwear fit. Small scuff mark on lower right elbow that lends it gorgeous rustic charm.",
    price: 95,
    originalPrice: 250,
    category: "Fashion",
    condition: "Fair",
    tags: ["Vintage", "Jacket", "Leather", "Suede", "Fashion"],
    image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=600&q=80",
    sellerId: "sell-22",
    sellerName: "Clara Jenkins",
    sellerRating: 4.2,
    sellerTrustScore: 78,
    trustRiskRating: "Medium",
    status: "active",
    views: 210,
    offersCount: 4,
    likesCount: 39,
    createdAt: "2026-05-10T12:00:00Z",
    trustAnalytics: "Newer seller account with few previous listing references. Suede texture verified via image check. Standard delivery suggested.",
  },
  {
    id: "prod-5",
    title: "Specialized Rockhopper Comp Mountain Bike (Medium)",
    description: "High quality aluminum mountain bike. Shimano shifting gears (1x9 speed drive). Tektro hydraulic disc brakes. Rides incredibly smoothly on forest tracks and roads. Front suspension has 100mm travel.",
    price: 490,
    originalPrice: 750,
    category: "Outdoors & Sports",
    condition: "Good",
    tags: ["Specialized", "Bike", "Mountain Bike", "Sports", "Cycling"],
    image: "https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&w=600&q=80",
    sellerId: "sell-11",
    sellerName: "Tyler Green",
    sellerRating: 4.6,
    sellerTrustScore: 89,
    trustRiskRating: "Low",
    status: "active",
    views: 312,
    offersCount: 5,
    likesCount: 51,
    createdAt: "2026-05-16T11:45:00Z",
    trustAnalytics: "Local lookup matches seller profile coordinates. Original frame code supplied during draft setup.",
  },
  {
    id: "prod-6",
    title: "Suspicious Super Cheap Rolex Submariner (Reported Flag)",
    description: "Brand new real Rolex Submariner watch. Super authentic, only selling for cheap because I need cash fast today. Don't ask questions just buy, ship only via private wire payment.",
    price: 350,
    originalPrice: 10000,
    category: "Fashion",
    condition: "New",
    tags: ["Rolex", "Watch", "Luxury", "Gold"],
    image: "https://images.unsplash.com/photo-1547996160-81dfa63595aa?auto=format&fit=crop&w=600&q=80",
    sellerId: "sell-999-bad",
    sellerName: "Scammer Dave",
    sellerRating: 1.2,
    sellerTrustScore: 15,
    trustRiskRating: "High",
    status: "moderation_review",
    views: 450,
    offersCount: 12,
    likesCount: 1,
    createdAt: "2026-05-20T11:00:00Z",
    moderationReason: "Extreme price mismatch. Requesting direct banking transfers instead of standard Vendoora high-trust Escrow. Flagged automatically by system heuristical safety filters.",
    trustAnalytics: "Extreme high risk discrepancy detected. Image matching generic catalog files index and description references out of platform transactions.",
  }
];

export const INITIAL_USER: UserProfile = {
  userId: "user-101",
  username: "Oladimeji Azeez",
  email: "oladimejiazeez052@gmail.com",
  role: "buyer", // Can toggle roles interactive
  trustScore: 98,
  walletBalance: 1250,
  avatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=150&q=80",
  listingsCreated: 2,
  purchasedCount: 14,
  salesCount: 8,
  onboardingStep: 0, // 0 = complete
};

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: "notif-1",
    title: "New AI Bargain Suggestion",
    description: "The buyer Alice Miller offered $780 for your iPhone 15 Pro. The Vendoora Smart Negotiator suggests counter-offering $820 for maximum yield.",
    type: "offer",
    read: false,
    timestamp: "2026-05-20T17:30:00Z",
  },
  {
    id: "notif-2",
    title: "Secure Escrow Funding Complete",
    description: "Your recent trade for Sony Headphones has been verified! Standard shipping labels are ready for download.",
    type: "order",
    read: true,
    timestamp: "2026-05-19T09:00:00Z",
  },
  {
    id: "notif-3",
    title: "Trust Rank Upgraded",
    description: "Outstanding behavior! Your Trust Score increased by +2 points due to rapid transaction processing and excellent buyer ratings.",
    type: "info",
    read: true,
    timestamp: "2026-05-18T12:00:00Z",
  }
];

export const INITIAL_ORDERS: Order[] = [
  {
    orderId: "ord-881",
    productId: "prod-2",
    productTitle: "Sony WH-1000XM4 Noise Canceling Wireless Headphones",
    productImage: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=150&q=80",
    price: 180,
    buyerId: "user-101",
    sellerId: "sell-88",
    sellerName: "Marcus Brody",
    status: "shipped",
    trackingNumber: "TRK-VEN-903912",
    createdAt: "2026-05-19T08:30:00Z",
  },
  {
    orderId: "ord-420",
    productId: "prod-3",
    productTitle: "Keychron Q1 Mechanical Keyboard (Hot-swappable)",
    productImage: "https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?auto=format&fit=crop&w=150&q=80",
    price: 130,
    buyerId: "user-buyer-abc",
    sellerId: "user-101",
    sellerName: "Oladimeji Azeez",
    status: "processing",
    createdAt: "2026-05-20T11:00:00Z",
  }
];

export const INITIAL_CHATS: ChatSession[] = [
  {
    chatId: "chat-active-1",
    productId: "prod-1",
    buyerId: "user-101",
    buyerName: "Oladimeji Azeez",
    currentOffer: 790,
    sellerMinPrice: 780,
    lastOfferSender: "buyer",
    status: "bargaining",
    lastUpdated: "2026-05-20T18:00:00Z",
    messages: [
      { id: "msg-1", sender: "system", text: "Automated Escrow Trade Chat initialized.", timestamp: "2026-05-20T17:00:00Z" },
      { id: "msg-2", sender: "seller", text: "Hey! The phone is in perfect shape. I raw-listed it at $850.", timestamp: "2026-05-20T17:02:00Z" },
      { id: "msg-3", sender: "buyer", text: "Would you take $750 for it today? Can meet up or shipping works.", timestamp: "2026-05-20T17:15:00Z", offerValue: 750 },
      { id: "msg-4", sender: "seller", text: "Oof, $750 is a bit low. I can get on board with $810 limit.", timestamp: "2026-05-20T17:22:00Z" },
      { id: "msg-5", sender: "buyer", text: "Can we settle right in the middle at $790?", timestamp: "2026-05-20T18:00:00Z", offerValue: 790 },
    ]
  },
  {
    chatId: "chat-active-2",
    productId: "prod-5",
    buyerId: "user-buyer-xyz",
    buyerName: "Sarah Higgins",
    currentOffer: 460,
    sellerMinPrice: 440,
    lastOfferSender: "buyer",
    status: "bargaining",
    lastUpdated: "2026-05-20T15:20:00Z",
    messages: [
      { id: "msg-10", sender: "system", text: "Trade chat open for Specialized Rockhopper Bike.", timestamp: "2026-05-20T15:00:00Z" },
      { id: "msg-11", sender: "buyer", text: "Hello! Is the bike suspension properly serviced?", timestamp: "2026-05-20T15:10:00Z" },
      { id: "msg-12", sender: "seller", text: "Hi Sarah! Yes, serviced last autumn. Front locks and seals work smoothly.", timestamp: "2026-05-20T15:15:00Z" },
      { id: "msg-13", sender: "buyer", text: "Sounds wonderful. I'd love to lock it in for $460.", timestamp: "2026-05-20T15:20:00Z", offerValue: 460 },
    ]
  }
];

export const CATEGORIES = [
  "All Categories",
  "Electronics",
  "Audio & Music",
  "Computer Gear",
  "Fashion",
  "Outdoors & Sports",
  "Home Furniture",
  "Books",
  "Other"
];

export const DESIGN_SYSTEM_COLORS = [
  { name: "Trust Blue (Core)", hex: "#2563EB", use: "Platform assurance, primary action triggers, escrow validation elements" },
  { name: "Growth Emerald", hex: "#10B981", use: "Completed sales, positive negotiation cues, wallet triggers, savings tracking" },
  { name: "Charcoal Deep", hex: "#111827", use: "Elegant headers, display typography accents, solid status layouts" },
  { name: "Slate Off-white", hex: "#F8FAFC", use: "Primary backdrop canvas, spacious negative spaces blocks" },
  { name: "Warning Amber", hex: "#F59E0B", use: "Pending negotiations status indicators, moderate warning risk indicators" },
  { name: "Alert Rust", hex: "#EF4444", use: "Flagged scam listings, deleted records feedback, banned entities indicators" }
];
