import { Product, ChatSession, UserProfile, Order, AppNotification } from "./types";

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    title: "iPhone 15 Pro (128GB, Space Black) - Unlocked",
    description: "Selling my fully-unlocked space black iPhone 15 Pro. Perfect condition, 100% battery capacity. Protected with glass screen protector since day 1. Includes original box and unused USB-C fast charging braided cable.",
    price: 850,
    originalPrice: 999,
    category: "Electronics",
    condition: "Like New",
    tags: ["iPhone", "Apple", "Smartphones", "Mobile", "Unlocked"],
    image: "https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?auto=format&fit=crop&w=600&q=80",
    sellerId: "sell-99",
    sellerName: "Alice Miller",
    sellerRating: 4.9,
    sellerTrustScore: 97,
    trustRiskRating: "Low",
    status: "active",
    views: 142,
    offersCount: 3,
    likesCount: 18,
    createdAt: "2026-05-18T10:00:00Z",
    trustAnalytics: "Genuine seller with 50+ successful completions. Original receipts scanned. Serial number validated successfully. High Trust ranking.",
  },
  {
    id: "prod-2",
    title: "Sony WH-1000XM4 Noise Canceling Wireless Headphones",
    description: "Selling because I upgraded. Active noise cancellation is completely phenomenal. Battery lasts 30+ hours easily. Comes with carrying case, headphone jack cable, and air travel adapter.",
    price: 180,
    originalPrice: 280,
    category: "Audio & Music",
    condition: "Good",
    tags: ["Headphones", "Sony", "ANC", "Wireless", "Audio"],
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&q=80",
    sellerId: "sell-88",
    sellerName: "Marcus Brody",
    sellerRating: 4.7,
    sellerTrustScore: 91,
    trustRiskRating: "Low",
    status: "active",
    views: 89,
    offersCount: 1,
    likesCount: 12,
    createdAt: "2026-05-15T08:30:00Z",
    trustAnalytics: "Authenticated model. Verified buyer reviews for seller match current coordinates. Account age > 2 years.",
  },
  {
    id: "prod-3",
    title: "Keychron Q1 Mechanical Keyboard (Hot-swappable)",
    description: "Keychron Q1 Pro fully assembled mechanical keyboard. Brown switches, custom tactile feelings. Premium CNC aluminum body with gorgeous sound. Includes coiled cable.",
    price: 130,
    originalPrice: 190,
    category: "Computer Gear",
    condition: "New",
    tags: ["Keyboard", "Mechanical", "Keychron", "Tech", "Custom"],
    image: "https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?auto=format&fit=crop&w=600&q=80",
    sellerId: "sell-55",
    sellerName: "Devin Zhao",
    sellerRating: 4.8,
    sellerTrustScore: 94,
    trustRiskRating: "Low",
    status: "active",
    views: 64,
    offersCount: 0,
    likesCount: 7,
    createdAt: "2026-05-19T14:15:00Z",
    trustAnalytics: "Listing aligns with standard seller inventory. Clear product photoshoot matches standard desk lighting. No generic stock tags found.",
  },
  {
    id: "prod-4",
    title: "Vintage Heavy Suede Leather Jacket - Dark Brown",
    description: "Stunning vintage genuine dark brown suede leather jacket. Warm quilted inner lining. Great streetwear fit. Small scuff mark on lower right elbow that lends it gorgeous rustic charm.",
    price: 95,
    originalPrice: 250,
    category: "Fashion",
    condition: "Fair",
    tags: ["Vintage", "Jacket", "Leather", "Suede", "Fashion"],
    image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=600&q=80",
    sellerId: "sell-22",
    sellerName: "Clara Jenkins",
    sellerRating: 4.2,
    sellerTrustScore: 78,
    trustRiskRating: "Medium",
    status: "active",
    views: 210,
    offersCount: 4,
    likesCount: 39,
    createdAt: "2026-05-10T12:00:00Z",
    trustAnalytics: "Newer seller account with few previous listing references. Suede texture verified via image check. Standard delivery suggested.",
  },
  {
    id: "prod-5",
    title: "Specialized Rockhopper Comp Mountain Bike (Medium)",
    description: "High quality aluminum mountain bike. Shimano shifting gears (1x9 speed drive). Tektro hydraulic disc brakes. Rides incredibly smoothly on forest tracks and roads. Front suspension has 100mm travel.",
    price: 490,
    originalPrice: 750,
    category: "Outdoors & Sports",
    condition: "Good",
    tags: ["Specialized", "Bike", "Mountain Bike", "Sports", "Cycling"],
    image: "https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&w=600&q=80",
    sellerId: "sell-11",
    sellerName: "Tyler Green",
    sellerRating: 4.6,
    sellerTrustScore: 89,
    trustRiskRating: "Low",
    status: "active",
    views: 312,
    offersCount: 5,
    likesCount: 51,
    createdAt: "2026-05-16T11:45:00Z",
    trustAnalytics: "Local lookup matches seller profile coordinates. Original frame code supplied during draft setup.",
  },
  {
    id: "prod-6",
    title: "Suspicious Super Cheap Rolex Submariner (Reported Flag)",
    description: "Brand new real Rolex Submariner watch. Super authentic, only selling for cheap because I need cash fast today. Don't ask questions just buy, ship only via private wire payment.",
    price: 350,
    originalPrice: 10000,
    category: "Fashion",
    condition: "New",
    tags: ["Rolex", "Watch", "Luxury", "Gold"],
    image: "https://images.unsplash.com/photo-1547996160-81dfa63595aa?auto=format&fit=crop&w=600&q=80",
    sellerId: "sell-999-bad",
    sellerName: "Scammer Dave",
    sellerRating: 1.2,
    sellerTrustScore: 15,
    trustRiskRating: "High",
    status: "moderation_review",
    views: 450,
    offersCount: 12,
    likesCount: 1,
    createdAt: "2026-05-20T11:00:00Z",
    moderationReason: "Extreme price mismatch. Requesting direct banking transfers instead of standard Vendoora high-trust Escrow. Flagged automatically by system heuristical safety filters.",
    trustAnalytics: "Extreme high risk discrepancy detected. Image matching generic catalog files index and description references out of platform transactions.",
  },
  {
    id: "prod-watch-1",
    title: "Architectural Watch",
    description: "Selling my beautiful minimalist Architectural Watch. Stainless steel casing, sapphire crystal face, genuine leather strap. Original packaging included.",
    price: 295,
    originalPrice: 350,
    category: "Fashion",
    condition: "Like New",
    tags: ["Watch", "Minimalist", "Premium", "Chronograph"],
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAmu933KExLMRhD3WE-nRuInf824T-ZD7WXPsMxUcJJdw-AC1hHz2aUh0hbrwHfHwsxZ9GbBwLQjbSPQ_dE1TUejWnAnAktun73412A88I4rcpmzgl2U9ulQ24nCUERd_gQ7PuK1SyzvRrQRHcmD-9EW8bdzYgZnYxm8dDZyCR9IL3JTPoaT6BbtlzcwmLW8wP22jx3HDI9K-LywOnptvUPP3UoW-YU5bLMszrKrQXtyjnNuI3UWAwKC_rMWcwbcd85Bza2G3tsi4w",
    sellerId: "sell-sarah-j",
    sellerName: "Sarah Jenkins",
    sellerRating: 4.9,
    sellerTrustScore: 99,
    trustRiskRating: "Low",
    status: "active",
    views: 104,
    offersCount: 1,
    likesCount: 42,
    createdAt: "2026-05-20T10:00:00Z",
    trustAnalytics: "Verified double-lock merchant. Top ratings in vintage and modern style pieces.",
  },
  {
    id: "prod-mcc-1",
    title: "Minimalist Oak Coffee Table",
    description: "Every piece is handcrafted in our Seattle studio with a focus on sustainable sourcing and architectural integrity. Curated bespoke timber and steel fittings.",
    price: 849,
    originalPrice: 1100,
    category: "Home Furniture",
    condition: "New",
    tags: ["Table", "Oak", "Woodworking", "Modern Craft Co."],
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuC80x-EcfI3UlwKFwL91id8iLiJf8xiBXFF5Gi7ND066zoHx1KlKXR8Gi6-TJ_57NZXAEdpTvAUbZaFnYAEbY2T7l67mSmcsOd9rKh_Jr5smVFR9Vcf4JQlPxyTw-QjrcmdT1OB3l1wM9J7faW3V-YDkqBZSb32fNbmHhvr2C36tvmMkILYQrZKEHUgViaizWzns8krLe2BPeKTF7_BakUxN8f1F8qMMkEmtxx_UuPTAlN_R-DyzK80TDUn6ppzuwxUBTLUlsTS7tQ",
    sellerId: "sell-mcc",
    sellerName: "Modern Craft Co.",
    sellerRating: 4.9,
    sellerTrustScore: 99,
    trustRiskRating: "Low",
    status: "active",
    views: 312,
    offersCount: 4,
    likesCount: 88,
    createdAt: "2026-05-21T09:00:00Z",
    trustAnalytics: "Master craftsman profile verified. Handcrafted furniture series. Standard shipping protected.",
  },
  {
    id: "prod-mcc-2",
    title: "Organic Form Ceramic Vases",
    description: "Studio-fired organic form ceramic vases with subtle textured glaze. Perfect as sculptural home decor accents.",
    price: 125,
    originalPrice: 150,
    category: "Other",
    condition: "New",
    tags: ["Ceramic", "Vase", "Sculpture", "Modern Craft Co."],
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAJekjV-Gjb4AB_flt8F7rvLucXAUw6DnvRBNRZzAPo2rBUVkfk2ZcVtO4mVqqmfjL24X8_d_si6tBfOqeD12p4zmtStlSVpYpdj9g7cC1SHgwaC-zdgYe_2BUGTR-mBuqFoXr-Z-zhsbGU4--3jpMAJAPWpv0LBP-ruLo98KmNKWcYjmjSdPMbVJKzfSJo2cZrnQ99L-sOTbYwewLIMb4lvnk0ONT5UXV7mk3reDgpD0TZJBfkbVUUZ76B1JxJI3pEFU9EsrbjyKU",
    sellerId: "sell-mcc",
    sellerName: "Modern Craft Co.",
    sellerRating: 4.9,
    sellerTrustScore: 99,
    trustRiskRating: "Low",
    status: "active",
    views: 145,
    offersCount: 1,
    likesCount: 39,
    createdAt: "2026-05-21T09:15:00Z",
    trustAnalytics: "Verified collection items. Carefully packed for protective escrow delivery.",
  },
  {
    id: "prod-mcc-3",
    title: "Executive Walnut Desk Tray",
    description: "Milled from a single block of black walnut wood, this desk organizer keeps key accessories neatly arranged.",
    price: 210,
    originalPrice: 245,
    category: "Computer Gear",
    condition: "New",
    tags: ["Walnut", "Organizer", "Tray", "Modern Craft Co."],
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCOHI49fUg-KorkXjyWWdmPW_f7s_tKDUjYV4-LjsBvSCP0QuTca9w7qz_1QZGoXjOVblY3lwi3tLTK5UtYLeRucmfe5oaaoLiA_AS_YwmgcPiap5HVM2o2doN05TOMAwefxE1SVwVeZOyhGKEigrD9613OrKqPrbg1ComxeHNcaO803M_aDvK-8tpPXIKkmHqg7f4DOtsg6SkBB2T70hmYTcj4GbPcCfI2AXSwojudnHQ6nP2Y6GFiaNQ8xN2ldDaLQzXBknb97e8",
    sellerId: "sell-mcc",
    sellerName: "Modern Craft Co.",
    sellerRating: 4.9,
    sellerTrustScore: 99,
    trustRiskRating: "Low",
    status: "active",
    views: 95,
    offersCount: 0,
    likesCount: 20,
    createdAt: "2026-05-21T09:30:00Z",
    trustAnalytics: "Eco-sourced timber logs coordinates validated.",
  },
  {
    id: "prod-mcc-4",
    title: "Industrial Copper Pendant",
    description: "Curated spun raw copper pendant ceiling lamps with industrial fixtures. Emits an incredibly warm amber tone glow.",
    price: 185,
    originalPrice: 220,
    category: "Other",
    condition: "New",
    tags: ["Lamp", "Pendant", "Copper", "Modern Craft Co."],
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCoaw_uOloHtQX2g0pk9d3fi05HtbuM_kAQb7DjAFYWI_lBhTo_NXCYI-yjJzQqxSn-abkWZmaZWBKOAQKy6AkIQEQdeEWQktyI-VnV5_77kaUwsO1no4HxI8SL3P42SM_byFiApGNtm1aPrCWlbGCdgsGeqwZrfh6k6pRjawsa98YKsiehhqIbheQcxkBA36LAPWBFZNEYk3gkU8nsdUErrB1N2miWVkDL6ipwBH6eXZrrwuSySfzNKOrqh2wBMY2NNTXWDFl7puw",
    sellerId: "sell-mcc",
    sellerName: "Modern Craft Co.",
    sellerRating: 4.9,
    sellerTrustScore: 99,
    trustRiskRating: "Low",
    status: "active",
    views: 180,
    offersCount: 2,
    likesCount: 44,
    createdAt: "2026-05-19T10:00:00Z",
    trustAnalytics: "Electrical components certified and physical structure checked.",
  }
];

export const INITIAL_USER: UserProfile = {
  userId: "user-101",
  username: "Oladimeji Azeez",
  email: "oladimejiazeez052@gmail.com",
  role: "buyer", // Can toggle roles interactive
  trustScore: 98,
  walletBalance: 1250,
  avatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=150&q=80",
  listingsCreated: 2,
  purchasedCount: 14,
  salesCount: 8,
  onboardingStep: 0, // 0 = complete
};

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: "notif-1",
    title: "New AI Bargain Suggestion",
    description: "The buyer Alice Miller offered $780 for your iPhone 15 Pro. The Vendoora Smart Negotiator suggests counter-offering $820 for maximum yield.",
    type: "offer",
    read: false,
    timestamp: "2026-05-20T17:30:00Z",
  },
  {
    id: "notif-2",
    title: "Secure Escrow Funding Complete",
    description: "Your recent trade for Sony Headphones has been verified! Standard shipping labels are ready for download.",
    type: "order",
    read: true,
    timestamp: "2026-05-19T09:00:00Z",
  },
  {
    id: "notif-3",
    title: "Trust Rank Upgraded",
    description: "Outstanding behavior! Your Trust Score increased by +2 points due to rapid transaction processing and excellent buyer ratings.",
    type: "info",
    read: true,
    timestamp: "2026-05-18T12:00:00Z",
  }
];

export const INITIAL_ORDERS: Order[] = [
  {
    orderId: "ord-881",
    productId: "prod-2",
    productTitle: "Sony WH-1000XM4 Noise Canceling Wireless Headphones",
    productImage: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=150&q=80",
    price: 180,
    buyerId: "user-101",
    sellerId: "sell-88",
    sellerName: "Marcus Brody",
    status: "shipped",
    trackingNumber: "TRK-VEN-903912",
    createdAt: "2026-05-19T08:30:00Z",
  },
  {
    orderId: "ord-420",
    productId: "prod-3",
    productTitle: "Keychron Q1 Mechanical Keyboard (Hot-swappable)",
    productImage: "https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?auto=format&fit=crop&w=150&q=80",
    price: 130,
    buyerId: "user-buyer-abc",
    sellerId: "user-101",
    sellerName: "Oladimeji Azeez",
    status: "processing",
    createdAt: "2026-05-20T11:00:00Z",
  }
];

export const INITIAL_CHATS: ChatSession[] = [
  {
    chatId: "chat-sarah-jenkins",
    productId: "prod-watch-1",
    buyerId: "user-buyer-sarah",
    buyerName: "Sarah Jenkins",
    currentOffer: 265,
    sellerMinPrice: 250,
    lastOfferSender: "buyer",
    status: "bargaining",
    lastUpdated: "2026-05-20T10:45:00Z",
    messages: [
      {
        id: "msg-sarah-1",
        sender: "buyer",
        text: "Hi! I saw your listing for the Architectural Watch. It's beautiful. Would you be open to a slightly lower price?",
        timestamp: "10:42 AM"
      },
      {
        id: "msg-sarah-2",
        sender: "seller",
        text: "Hello Sarah! Thank you. I've only had it for a few months so I'm looking for something close to the asking price, but I'm open to reasonable offers.",
        timestamp: "10:44 AM"
      },
      {
        id: "msg-sarah-3",
        sender: "buyer",
        text: "I've sent an offer for the watch. Let me know if that works for you!",
        timestamp: "10:45 AM",
        offerValue: 265
      }
    ]
  },
  {
    chatId: "chat-david-chen",
    productId: "prod-mcc-1",
    buyerId: "user-buyer-david",
    buyerName: "David Chen",
    currentOffer: 800,
    sellerMinPrice: 780,
    lastOfferSender: "buyer",
    status: "bargaining",
    lastUpdated: "2026-05-19T14:20:00Z",
    messages: [
      {
        id: "msg-david-1",
        sender: "buyer",
        text: "Is the Minimalist Oak Coffee Table still available?",
        timestamp: "Yesterday"
      },
      {
        id: "msg-david-2",
        sender: "seller",
        text: "Hi David, yes indeed! Standard delivery or pick-up is doable.",
        timestamp: "Yesterday"
      }
    ]
  },
  {
    chatId: "chat-elena",
    productId: "prod-2",
    buyerId: "user-buyer-elena",
    buyerName: "Elena Rodriguez",
    currentOffer: 180,
    sellerMinPrice: 160,
    lastOfferSender: "buyer",
    status: "completed",
    lastUpdated: "2026-05-12T09:00:00Z",
    messages: [
      {
        id: "msg-elena-1",
        sender: "buyer",
        text: "Hello! Settle on $180 total cost?",
        timestamp: "Oct 12"
      },
      {
        id: "msg-elena-2",
        sender: "seller",
        text: "Sounds great! Deal accepted with standard fast escrow protective coordinates.",
        timestamp: "Oct 12"
      },
      {
        id: "msg-elena-3",
        sender: "buyer",
        text: "Thanks for the quick delivery! Package arrived safely.",
        timestamp: "Oct 15"
      }
    ]
  },
  {
    chatId: "chat-active-1",
    productId: "prod-1",
    buyerId: "user-101",
    buyerName: "Oladimeji Azeez",
    currentOffer: 790,
    sellerMinPrice: 780,
    lastOfferSender: "buyer",
    status: "bargaining",
    lastUpdated: "2026-05-20T18:00:00Z",
    messages: [
      { id: "msg-1", sender: "system", text: "Automated Escrow Trade Chat initialized.", timestamp: "2026-05-20T17:00:00Z" },
      { id: "msg-2", sender: "seller", text: "Hey! The phone is in perfect shape. I raw-listed it at $850.", timestamp: "2026-05-20T17:02:00Z" },
      { id: "msg-3", sender: "buyer", text: "Would you take $750 for it today? Can meet up or shipping works.", timestamp: "2026-05-20T17:15:00Z", offerValue: 750 },
      { id: "msg-4", sender: "seller", text: "Oof, $750 is a bit low. I can get on board with $810 limit.", timestamp: "2026-05-20T17:22:00Z" },
      { id: "msg-5", sender: "buyer", text: "Can we settle right in the middle at $790?", timestamp: "2026-05-20T18:00:00Z", offerValue: 790 },
    ]
  }
];

export const CATEGORIES = [
  "All Categories",
  "Electronics",
  "Audio & Music",
  "Computer Gear",
  "Fashion",
  "Outdoors & Sports",
  "Home Furniture",
  "Books",
  "Other"
];

export const DESIGN_SYSTEM_COLORS = [
  { name: "Trust Blue (Core)", hex: "#2563EB", use: "Platform assurance, primary action triggers, escrow validation elements" },
  { name: "Growth Emerald", hex: "#10B981", use: "Completed sales, positive negotiation cues, wallet triggers, savings tracking" },
  { name: "Charcoal Deep", hex: "#111827", use: "Elegant headers, display typography accents, solid status layouts" },
  { name: "Slate Off-white", hex: "#F8FAFC", use: "Primary backdrop canvas, spacious negative spaces blocks" },
  { name: "Warning Amber", hex: "#F59E0B", use: "Pending negotiations status indicators, moderate warning risk indicators" },
  { name: "Alert Rust", hex: "#EF4444", use: "Flagged scam listings, deleted records feedback, banned entities indicators" }
];
